on:
  pull_request:
    types: [ opened ]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: Pull Request Validator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Pull Request Validation
      uses: shovel-org/GithubActions@1.7.0
      env:
        GITH_EMAIL: subahua@qq.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
