on:
  schedule:
  - cron: '0 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: shovel-org/GithubActions@1.7.0
      env:
        GITH_EMAIL: subahua@qq.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
